import type { CodeSummarizer } from '../analysis/CodeSummarizer.js';
import type { CryptoDetector } from '../analysis/CryptoDetector.js';
import type { ExplainEngine } from '../analysis/ExplainEngine.js';
import type { RiskScorer } from '../analysis/RiskScorer.js';
import type { SessionReporter } from '../analysis/SessionReporter.js';
import type { StaticAnalyzer } from '../analysis/StaticAnalyzer.js';
import type { BrowserSessionManager } from '../browser/BrowserSessionManager.js';
import type { CodeCollector } from '../collector/CodeCollector.js';
import type { CompareAnchorRegistry } from '../compare/CompareAnchorRegistry.js';
import type { CompareAnchorSelector } from '../compare/CompareAnchorSelector.js';
import type { RequestChainCorrelator } from '../correlation/RequestChainCorrelator.js';
import type { Deobfuscator } from '../deobfuscation/Deobfuscator.js';
import type { BreakpointRegistry } from '../debugger/BreakpointRegistry.js';
import type { DebuggerEvidenceCorrelator } from '../debugger/DebuggerEvidenceCorrelator.js';
import type { DebuggerReportBuilder } from '../debugger/DebuggerReportBuilder.js';
import type { DebuggerSessionManager } from '../debugger/DebuggerSessionManager.js';
import type { PausedInspector } from '../debugger/PausedInspector.js';
import type { EvidenceStore } from '../evidence/EvidenceStore.js';
import type { AstIndexBuilder } from '../flow/AstIndexBuilder.js';
import type { FlowReasoningEngine } from '../flow/FlowReasoningEngine.js';
import type { FlowReasoningRegistry } from '../flow/FlowReasoningRegistry.js';
import type { BoundaryFixtureGenerator } from '../fixture/BoundaryFixtureGenerator.js';
import type { FixtureCandidateRegistry } from '../fixture/FixtureCandidateRegistry.js';
import type { HookManager } from '../hook/HookManager.js';
import type { IntermediateAlignment } from '../intermediate/IntermediateAlignment.js';
import type { IntermediateDiff } from '../intermediate/IntermediateDiff.js';
import type { IntermediateProbeRegistry } from '../intermediate/IntermediateProbeRegistry.js';
import type { NetworkCollector } from '../network/NetworkCollector.js';
import type { RequestInitiatorTracker } from '../network/RequestInitiatorTracker.js';
import type { XhrWatchpointManager } from '../network/xhrWatchpoints.js';
import type { PageController } from '../page/PageController.js';
import type { AcceptanceRecorder } from '../patch/AcceptanceRecorder.js';
import type { FixtureStabilizer } from '../patch/FixtureStabilizer.js';
import type { PatchApplier } from '../patch/PatchApplier.js';
import type { PatchLoopRunner } from '../patch/PatchLoopRunner.js';
import type { PatchPlanManager } from '../patch/PatchPlanManager.js';
import type { ScenarioPatchHintGenerator } from '../patch/ScenarioPatchHintGenerator.js';
import type { ScenarioPatchHintRegistry } from '../patch/ScenarioPatchHintRegistry.js';
import type { PatchPreflightPlanner } from '../patch-preflight/PatchPreflightPlanner.js';
import type { PatchPreflightRegistry } from '../patch-preflight/PatchPreflightRegistry.js';
import type { PurePreflightPlanner } from '../pure-preflight/PurePreflightPlanner.js';
import type { PurePreflightRegistry } from '../pure-preflight/PurePreflightRegistry.js';
import type { CrossLanguageDiff } from '../port/CrossLanguageDiff.js';
import type { CrossLanguageVerifier } from '../port/CrossLanguageVerifier.js';
import type { PythonPortExtractor } from '../port/PythonPortExtractor.js';
import type { UpgradeDiffRunner } from '../port/UpgradeDiffRunner.js';
import type { BoundaryDefiner } from '../pure/BoundaryDefiner.js';
import type { FreezeManager } from '../pure/FreezeManager.js';
import type { PureFixtureBuilder } from '../pure/PureFixtureBuilder.js';
import type { PureNodeExtractor } from '../pure/PureNodeExtractor.js';
import type { PureVerifier } from '../pure/PureVerifier.js';
import type { RuntimeTraceSampler } from '../pure/RuntimeTraceSampler.js';
import type { BaselineRegistry } from '../regression/BaselineRegistry.js';
import type { IntermediateRegressionRunner } from '../regression/IntermediateRegressionRunner.js';
import type { RegressionDiff } from '../regression/RegressionDiff.js';
import type { RegressionRunner } from '../regression/RegressionRunner.js';
import type { UpgradeRegressionRunner } from '../regression/UpgradeRegressionRunner.js';
import type { VersionedBaselineRegistry } from '../regression/VersionedBaselineRegistry.js';
import type { DeliveryReportBuilder } from '../report/DeliveryReportBuilder.js';
import type { CaptureReportBuilder } from '../report/CaptureReportBuilder.js';
import type { CompareAnchorReportBuilder } from '../report/CompareAnchorReportBuilder.js';
import type { FixtureCandidateReportBuilder } from '../report/FixtureCandidateReportBuilder.js';
import type { IntermediateRegressionReportBuilder } from '../report/IntermediateRegressionReportBuilder.js';
import type { PatchReportBuilder } from '../report/PatchReportBuilder.js';
import type { PatchPreflightReportBuilder } from '../report/PatchPreflightReportBuilder.js';
import type { PortReportBuilder } from '../report/PortReportBuilder.js';
import type { ProbePlanReportBuilder } from '../report/ProbePlanReportBuilder.js';
import type { PureReportBuilder } from '../report/PureReportBuilder.js';
import type { FlowReasoningReportBuilder } from '../report/FlowReasoningReportBuilder.js';
import type { PurePreflightReportBuilder } from '../report/PurePreflightReportBuilder.js';
import type { RebuildReportBuilder } from '../report/RebuildReportBuilder.js';
import type { RegressionReportBuilder } from '../report/RegressionReportBuilder.js';
import type { RebuildContextReportBuilder } from '../report/RebuildContextReportBuilder.js';
import type { ReverseReportBuilder } from '../report/ReverseReportBuilder.js';
import type { ScenarioReportBuilder } from '../report/ScenarioReportBuilder.js';
import type { ScenarioPatchHintReportBuilder } from '../report/ScenarioPatchHintReportBuilder.js';
import type { SdkReportBuilder } from '../report/SdkReportBuilder.js';
import type { TaskStateReportBuilder } from '../report/TaskStateReportBuilder.js';
import type { UpgradeReportBuilder } from '../report/UpgradeReportBuilder.js';
import type { WindowReportBuilder } from '../report/WindowReportBuilder.js';
import type { DivergenceComparator } from '../rebuild/DivergenceComparator.js';
import type { EnvAccessLogger } from '../rebuild/EnvAccessLogger.js';
import type { FixtureExtractor } from '../rebuild/FixtureExtractor.js';
import type { PatchAdvisor } from '../rebuild/PatchAdvisor.js';
import type { RebuildBundleExporter } from '../rebuild/RebuildBundleExporter.js';
import type { RebuildRunner } from '../rebuild/RebuildRunner.js';
import type { RebuildContextRegistry } from '../rebuild-integration/RebuildContextRegistry.js';
import type { RebuildInputResolver } from '../rebuild-integration/RebuildInputResolver.js';
import type { DeliveryAssembler } from '../sdk/DeliveryAssembler.js';
import type { DeliverySmokeTester } from '../sdk/DeliverySmokeTester.js';
import type { ProvenanceWriter } from '../sdk/ProvenanceWriter.js';
import type { SDKPackager } from '../sdk/SDKPackager.js';
import type { HelperBoundaryExtractor } from '../helper/HelperBoundaryExtractor.js';
import type { HelperBoundaryRegistry } from '../helper/HelperBoundaryRegistry.js';
import type { CapturePresetRegistry } from '../replay/CapturePresetRegistry.js';
import type { ReplayActionRunner } from '../replay/ReplayActionRunner.js';
import type { ReplayRecipeRunner } from '../replay/ReplayRecipeRunner.js';
import type { ProbePlanRegistry } from '../probe/ProbePlanRegistry.js';
import type { ScenarioProbePlanner } from '../probe/ScenarioProbePlanner.js';
import type { CryptoHelperLocator } from '../scenario/CryptoHelperLocator.js';
import type { RequestSinkLocator } from '../scenario/RequestSinkLocator.js';
import type { ScenarioActionPlanner } from '../scenario/ScenarioActionPlanner.js';
import type { ScenarioPresetRegistry } from '../scenario/ScenarioPresetRegistry.js';
import type { ScenarioWorkflowRunner } from '../scenario/ScenarioWorkflowRunner.js';
import type { SignatureScenarioAnalyzer } from '../scenario/SignatureScenarioAnalyzer.js';
import type { TokenScenarioAnalyzer } from '../scenario/TokenScenarioAnalyzer.js';
import type { StageGateEvaluator } from '../task/StageGateEvaluator.js';
import type { TaskManifestManager } from '../task/TaskManifestManager.js';
import type { AnalyzeTargetRunner } from '../workflow/AnalyzeTargetRunner.js';
import type { DeliveryHardeningRunner } from '../workflow/DeliveryHardeningRunner.js';
import type { DeliveryWorkflowRunner } from '../workflow/DeliveryWorkflowRunner.js';
import type { PatchWorkflowRunner } from '../workflow/PatchWorkflowRunner.js';
import type { PortWorkflowRunner } from '../workflow/PortWorkflowRunner.js';
import type { PureExtractionRunner } from '../workflow/PureExtractionRunner.js';
import type { RebuildWorkflowRunner } from '../workflow/RebuildWorkflowRunner.js';
import type { RegressionWorkflowRunner } from '../workflow/RegressionWorkflowRunner.js';
import type { ReverseWorkflowRunner } from '../workflow/ReverseWorkflowRunner.js';
import type { UpgradeWorkflowRunner } from '../workflow/UpgradeWorkflowRunner.js';
import type { DependencyWindowExtractor } from '../window/DependencyWindowExtractor.js';
import type { DependencyWindowRegistry } from '../window/DependencyWindowRegistry.js';

export interface AppRuntimeServices {
  browserSession: BrowserSessionManager;
  pageController: PageController;
  codeCollector: CodeCollector;
  codeSummarizer: CodeSummarizer;
  staticAnalyzer: StaticAnalyzer;
  cryptoDetector: CryptoDetector;
  riskScorer: RiskScorer;
  sessionReporter: SessionReporter;
  explainEngine: ExplainEngine;
  deobfuscator: Deobfuscator;
  requestChainCorrelator: RequestChainCorrelator;
  reverseReportBuilder: ReverseReportBuilder;
  rebuildBundleExporter: RebuildBundleExporter;
  rebuildRunner: RebuildRunner;
  envAccessLogger: EnvAccessLogger;
  fixtureExtractor: FixtureExtractor;
  divergenceComparator: DivergenceComparator;
  patchAdvisor: PatchAdvisor;
  patchPlanManager: PatchPlanManager;
  patchApplier: PatchApplier;
  patchLoopRunner: PatchLoopRunner;
  acceptanceRecorder: AcceptanceRecorder;
  fixtureStabilizer: FixtureStabilizer;
  patchWorkflowRunner: PatchWorkflowRunner;
  patchReportBuilder: PatchReportBuilder;
  freezeManager: FreezeManager;
  runtimeTraceSampler: RuntimeTraceSampler;
  boundaryDefiner: BoundaryDefiner;
  pureFixtureBuilder: PureFixtureBuilder;
  pureNodeExtractor: PureNodeExtractor;
  pureVerifier: PureVerifier;
  pureExtractionRunner: PureExtractionRunner;
  pureReportBuilder: PureReportBuilder;
  pythonPortExtractor: PythonPortExtractor;
  crossLanguageVerifier: CrossLanguageVerifier;
  crossLanguageDiff: CrossLanguageDiff;
  upgradeDiffRunner: UpgradeDiffRunner;
  portWorkflowRunner: PortWorkflowRunner;
  portReportBuilder: PortReportBuilder;
  rebuildWorkflowRunner: RebuildWorkflowRunner;
  rebuildReportBuilder: RebuildReportBuilder;
  hookManager: HookManager;
  networkCollector: NetworkCollector;
  requestInitiatorTracker: RequestInitiatorTracker;
  xhrWatchpointManager: XhrWatchpointManager;
  evidenceStore: EvidenceStore;
  taskManifestManager: TaskManifestManager;
  stageGateEvaluator: StageGateEvaluator;
  intermediateProbeRegistry: IntermediateProbeRegistry;
  intermediateAlignment: IntermediateAlignment;
  intermediateDiff: IntermediateDiff;
  baselineRegistry: BaselineRegistry;
  versionedBaselineRegistry: VersionedBaselineRegistry;
  regressionRunner: RegressionRunner;
  intermediateRegressionRunner: IntermediateRegressionRunner;
  upgradeRegressionRunner: UpgradeRegressionRunner;
  regressionDiff: RegressionDiff;
  sdkPackager: SDKPackager;
  deliveryAssembler: DeliveryAssembler;
  deliverySmokeTester: DeliverySmokeTester;
  provenanceWriter: ProvenanceWriter;
  taskStateReportBuilder: TaskStateReportBuilder;
  intermediateRegressionReportBuilder: IntermediateRegressionReportBuilder;
  regressionReportBuilder: RegressionReportBuilder;
  sdkReportBuilder: SdkReportBuilder;
  upgradeReportBuilder: UpgradeReportBuilder;
  deliveryReportBuilder: DeliveryReportBuilder;
  regressionWorkflowRunner: RegressionWorkflowRunner;
  upgradeWorkflowRunner: UpgradeWorkflowRunner;
  deliveryWorkflowRunner: DeliveryWorkflowRunner;
  deliveryHardeningRunner: DeliveryHardeningRunner;
  reverseWorkflowRunner: ReverseWorkflowRunner;
  analyzeTargetRunner: AnalyzeTargetRunner;
  signatureScenarioAnalyzer: SignatureScenarioAnalyzer;
  tokenScenarioAnalyzer: TokenScenarioAnalyzer;
  requestSinkLocator: RequestSinkLocator;
  cryptoHelperLocator: CryptoHelperLocator;
  scenarioPresetRegistry: ScenarioPresetRegistry;
  scenarioActionPlanner: ScenarioActionPlanner;
  scenarioWorkflowRunner: ScenarioWorkflowRunner;
  scenarioReportBuilder: ScenarioReportBuilder;
  capturePresetRegistry: CapturePresetRegistry;
  replayActionRunner: ReplayActionRunner;
  replayRecipeRunner: ReplayRecipeRunner;
  helperBoundaryExtractor: HelperBoundaryExtractor;
  helperBoundaryRegistry: HelperBoundaryRegistry;
  captureReportBuilder: CaptureReportBuilder;
  dependencyWindowExtractor: DependencyWindowExtractor;
  dependencyWindowRegistry: DependencyWindowRegistry;
  scenarioProbePlanner: ScenarioProbePlanner;
  probePlanRegistry: ProbePlanRegistry;
  windowReportBuilder: WindowReportBuilder;
  probePlanReportBuilder: ProbePlanReportBuilder;
  boundaryFixtureGenerator: BoundaryFixtureGenerator;
  fixtureCandidateRegistry: FixtureCandidateRegistry;
  scenarioPatchHintGenerator: ScenarioPatchHintGenerator;
  scenarioPatchHintRegistry: ScenarioPatchHintRegistry;
  fixtureCandidateReportBuilder: FixtureCandidateReportBuilder;
  scenarioPatchHintReportBuilder: ScenarioPatchHintReportBuilder;
  debuggerSessionManager: DebuggerSessionManager;
  breakpointRegistry: BreakpointRegistry;
  pausedInspector: PausedInspector;
  debuggerEvidenceCorrelator: DebuggerEvidenceCorrelator;
  debuggerReportBuilder: DebuggerReportBuilder;
  compareAnchorSelector: CompareAnchorSelector;
  compareAnchorRegistry: CompareAnchorRegistry;
  compareAnchorReportBuilder: CompareAnchorReportBuilder;
  patchPreflightPlanner: PatchPreflightPlanner;
  patchPreflightRegistry: PatchPreflightRegistry;
  patchPreflightReportBuilder: PatchPreflightReportBuilder;
  rebuildInputResolver: RebuildInputResolver;
  rebuildContextRegistry: RebuildContextRegistry;
  rebuildContextReportBuilder: RebuildContextReportBuilder;
  astIndexBuilder: AstIndexBuilder;
  flowReasoningEngine: FlowReasoningEngine;
  flowReasoningRegistry: FlowReasoningRegistry;
  flowReasoningReportBuilder: FlowReasoningReportBuilder;
  purePreflightPlanner: PurePreflightPlanner;
  purePreflightRegistry: PurePreflightRegistry;
  purePreflightReportBuilder: PurePreflightReportBuilder;
}
