import type { CodeSummarizer } from '../analysis/CodeSummarizer.js';
import type { CryptoDetector } from '../analysis/CryptoDetector.js';
import type { ExplainEngine } from '../analysis/ExplainEngine.js';
import type { RiskScorer } from '../analysis/RiskScorer.js';
import type { SessionReporter } from '../analysis/SessionReporter.js';
import type { StaticAnalyzer } from '../analysis/StaticAnalyzer.js';
import type { BrowserSessionManager } from '../browser/BrowserSessionManager.js';
import type { CodeCollector } from '../collector/CodeCollector.js';
import type { RequestChainCorrelator } from '../correlation/RequestChainCorrelator.js';
import type { Deobfuscator } from '../deobfuscation/Deobfuscator.js';
import type { EvidenceStore } from '../evidence/EvidenceStore.js';
import type { HookManager } from '../hook/HookManager.js';
import type { IntermediateAlignment } from '../intermediate/IntermediateAlignment.js';
import type { IntermediateDiff } from '../intermediate/IntermediateDiff.js';
import type { IntermediateProbeRegistry } from '../intermediate/IntermediateProbeRegistry.js';
import type { NetworkCollector } from '../network/NetworkCollector.js';
import type { RequestInitiatorTracker } from '../network/RequestInitiatorTracker.js';
import type { XhrWatchpointManager } from '../network/xhrWatchpoints.js';
import type { PageController } from '../page/PageController.js';
import type { AcceptanceRecorder } from '../patch/AcceptanceRecorder.js';
import type { FixtureStabilizer } from '../patch/FixtureStabilizer.js';
import type { PatchApplier } from '../patch/PatchApplier.js';
import type { PatchLoopRunner } from '../patch/PatchLoopRunner.js';
import type { PatchPlanManager } from '../patch/PatchPlanManager.js';
import type { CrossLanguageDiff } from '../port/CrossLanguageDiff.js';
import type { CrossLanguageVerifier } from '../port/CrossLanguageVerifier.js';
import type { PythonPortExtractor } from '../port/PythonPortExtractor.js';
import type { UpgradeDiffRunner } from '../port/UpgradeDiffRunner.js';
import type { BoundaryDefiner } from '../pure/BoundaryDefiner.js';
import type { FreezeManager } from '../pure/FreezeManager.js';
import type { PureFixtureBuilder } from '../pure/PureFixtureBuilder.js';
import type { PureNodeExtractor } from '../pure/PureNodeExtractor.js';
import type { PureVerifier } from '../pure/PureVerifier.js';
import type { RuntimeTraceSampler } from '../pure/RuntimeTraceSampler.js';
import type { BaselineRegistry } from '../regression/BaselineRegistry.js';
import type { IntermediateRegressionRunner } from '../regression/IntermediateRegressionRunner.js';
import type { RegressionDiff } from '../regression/RegressionDiff.js';
import type { RegressionRunner } from '../regression/RegressionRunner.js';
import type { UpgradeRegressionRunner } from '../regression/UpgradeRegressionRunner.js';
import type { VersionedBaselineRegistry } from '../regression/VersionedBaselineRegistry.js';
import type { DeliveryReportBuilder } from '../report/DeliveryReportBuilder.js';
import type { IntermediateRegressionReportBuilder } from '../report/IntermediateRegressionReportBuilder.js';
import type { PatchReportBuilder } from '../report/PatchReportBuilder.js';
import type { PortReportBuilder } from '../report/PortReportBuilder.js';
import type { PureReportBuilder } from '../report/PureReportBuilder.js';
import type { RebuildReportBuilder } from '../report/RebuildReportBuilder.js';
import type { RegressionReportBuilder } from '../report/RegressionReportBuilder.js';
import type { ReverseReportBuilder } from '../report/ReverseReportBuilder.js';
import type { SdkReportBuilder } from '../report/SdkReportBuilder.js';
import type { TaskStateReportBuilder } from '../report/TaskStateReportBuilder.js';
import type { UpgradeReportBuilder } from '../report/UpgradeReportBuilder.js';
import type { DivergenceComparator } from '../rebuild/DivergenceComparator.js';
import type { EnvAccessLogger } from '../rebuild/EnvAccessLogger.js';
import type { FixtureExtractor } from '../rebuild/FixtureExtractor.js';
import type { PatchAdvisor } from '../rebuild/PatchAdvisor.js';
import type { RebuildBundleExporter } from '../rebuild/RebuildBundleExporter.js';
import type { RebuildRunner } from '../rebuild/RebuildRunner.js';
import type { DeliveryAssembler } from '../sdk/DeliveryAssembler.js';
import type { DeliverySmokeTester } from '../sdk/DeliverySmokeTester.js';
import type { ProvenanceWriter } from '../sdk/ProvenanceWriter.js';
import type { SDKPackager } from '../sdk/SDKPackager.js';
import type { StageGateEvaluator } from '../task/StageGateEvaluator.js';
import type { TaskManifestManager } from '../task/TaskManifestManager.js';
import type { AnalyzeTargetRunner } from '../workflow/AnalyzeTargetRunner.js';
import type { DeliveryHardeningRunner } from '../workflow/DeliveryHardeningRunner.js';
import type { DeliveryWorkflowRunner } from '../workflow/DeliveryWorkflowRunner.js';
import type { PatchWorkflowRunner } from '../workflow/PatchWorkflowRunner.js';
import type { PortWorkflowRunner } from '../workflow/PortWorkflowRunner.js';
import type { PureExtractionRunner } from '../workflow/PureExtractionRunner.js';
import type { RebuildWorkflowRunner } from '../workflow/RebuildWorkflowRunner.js';
import type { RegressionWorkflowRunner } from '../workflow/RegressionWorkflowRunner.js';
import type { ReverseWorkflowRunner } from '../workflow/ReverseWorkflowRunner.js';
import type { UpgradeWorkflowRunner } from '../workflow/UpgradeWorkflowRunner.js';

export interface AppRuntimeServices {
  browserSession: BrowserSessionManager;
  pageController: PageController;
  codeCollector: CodeCollector;
  codeSummarizer: CodeSummarizer;
  staticAnalyzer: StaticAnalyzer;
  cryptoDetector: CryptoDetector;
  riskScorer: RiskScorer;
  sessionReporter: SessionReporter;
  explainEngine: ExplainEngine;
  deobfuscator: Deobfuscator;
  requestChainCorrelator: RequestChainCorrelator;
  reverseReportBuilder: ReverseReportBuilder;
  rebuildBundleExporter: RebuildBundleExporter;
  rebuildRunner: RebuildRunner;
  envAccessLogger: EnvAccessLogger;
  fixtureExtractor: FixtureExtractor;
  divergenceComparator: DivergenceComparator;
  patchAdvisor: PatchAdvisor;
  patchPlanManager: PatchPlanManager;
  patchApplier: PatchApplier;
  patchLoopRunner: PatchLoopRunner;
  acceptanceRecorder: AcceptanceRecorder;
  fixtureStabilizer: FixtureStabilizer;
  patchWorkflowRunner: PatchWorkflowRunner;
  patchReportBuilder: PatchReportBuilder;
  freezeManager: FreezeManager;
  runtimeTraceSampler: RuntimeTraceSampler;
  boundaryDefiner: BoundaryDefiner;
  pureFixtureBuilder: PureFixtureBuilder;
  pureNodeExtractor: PureNodeExtractor;
  pureVerifier: PureVerifier;
  pureExtractionRunner: PureExtractionRunner;
  pureReportBuilder: PureReportBuilder;
  pythonPortExtractor: PythonPortExtractor;
  crossLanguageVerifier: CrossLanguageVerifier;
  crossLanguageDiff: CrossLanguageDiff;
  upgradeDiffRunner: UpgradeDiffRunner;
  portWorkflowRunner: PortWorkflowRunner;
  portReportBuilder: PortReportBuilder;
  rebuildWorkflowRunner: RebuildWorkflowRunner;
  rebuildReportBuilder: RebuildReportBuilder;
  hookManager: HookManager;
  networkCollector: NetworkCollector;
  requestInitiatorTracker: RequestInitiatorTracker;
  xhrWatchpointManager: XhrWatchpointManager;
  evidenceStore: EvidenceStore;
  taskManifestManager: TaskManifestManager;
  stageGateEvaluator: StageGateEvaluator;
  intermediateProbeRegistry: IntermediateProbeRegistry;
  intermediateAlignment: IntermediateAlignment;
  intermediateDiff: IntermediateDiff;
  baselineRegistry: BaselineRegistry;
  versionedBaselineRegistry: VersionedBaselineRegistry;
  regressionRunner: RegressionRunner;
  intermediateRegressionRunner: IntermediateRegressionRunner;
  upgradeRegressionRunner: UpgradeRegressionRunner;
  regressionDiff: RegressionDiff;
  sdkPackager: SDKPackager;
  deliveryAssembler: DeliveryAssembler;
  deliverySmokeTester: DeliverySmokeTester;
  provenanceWriter: ProvenanceWriter;
  taskStateReportBuilder: TaskStateReportBuilder;
  intermediateRegressionReportBuilder: IntermediateRegressionReportBuilder;
  regressionReportBuilder: RegressionReportBuilder;
  sdkReportBuilder: SdkReportBuilder;
  upgradeReportBuilder: UpgradeReportBuilder;
  deliveryReportBuilder: DeliveryReportBuilder;
  regressionWorkflowRunner: RegressionWorkflowRunner;
  upgradeWorkflowRunner: UpgradeWorkflowRunner;
  deliveryWorkflowRunner: DeliveryWorkflowRunner;
  deliveryHardeningRunner: DeliveryHardeningRunner;
  reverseWorkflowRunner: ReverseWorkflowRunner;
  analyzeTargetRunner: AnalyzeTargetRunner;
}
