import type { CodeSummarizer } from '../analysis/CodeSummarizer.js';
import type { CryptoDetector } from '../analysis/CryptoDetector.js';
import type { ExplainEngine } from '../analysis/ExplainEngine.js';
import type { RiskScorer } from '../analysis/RiskScorer.js';
import type { SessionReporter } from '../analysis/SessionReporter.js';
import type { StaticAnalyzer } from '../analysis/StaticAnalyzer.js';
import type { BrowserSessionManager } from '../browser/BrowserSessionManager.js';
import type { CodeCollector } from '../collector/CodeCollector.js';
import type { RequestChainCorrelator } from '../correlation/RequestChainCorrelator.js';
import type { Deobfuscator } from '../deobfuscation/Deobfuscator.js';
import type { EvidenceStore } from '../evidence/EvidenceStore.js';
import type { HookManager } from '../hook/HookManager.js';
import type { NetworkCollector } from '../network/NetworkCollector.js';
import type { RequestInitiatorTracker } from '../network/RequestInitiatorTracker.js';
import type { XhrWatchpointManager } from '../network/xhrWatchpoints.js';
import type { PageController } from '../page/PageController.js';
import type { AcceptanceRecorder } from '../patch/AcceptanceRecorder.js';
import type { FixtureStabilizer } from '../patch/FixtureStabilizer.js';
import type { PatchApplier } from '../patch/PatchApplier.js';
import type { PatchLoopRunner } from '../patch/PatchLoopRunner.js';
import type { PatchPlanManager } from '../patch/PatchPlanManager.js';
import type { PatchReportBuilder } from '../report/PatchReportBuilder.js';
import type { RebuildReportBuilder } from '../report/RebuildReportBuilder.js';
import type { ReverseReportBuilder } from '../report/ReverseReportBuilder.js';
import type { DivergenceComparator } from '../rebuild/DivergenceComparator.js';
import type { EnvAccessLogger } from '../rebuild/EnvAccessLogger.js';
import type { FixtureExtractor } from '../rebuild/FixtureExtractor.js';
import type { PatchAdvisor } from '../rebuild/PatchAdvisor.js';
import type { RebuildBundleExporter } from '../rebuild/RebuildBundleExporter.js';
import type { RebuildRunner } from '../rebuild/RebuildRunner.js';
import type { AnalyzeTargetRunner } from '../workflow/AnalyzeTargetRunner.js';
import type { PatchWorkflowRunner } from '../workflow/PatchWorkflowRunner.js';
import type { RebuildWorkflowRunner } from '../workflow/RebuildWorkflowRunner.js';
import type { ReverseWorkflowRunner } from '../workflow/ReverseWorkflowRunner.js';

export interface AppRuntimeServices {
  browserSession: BrowserSessionManager;
  pageController: PageController;
  codeCollector: CodeCollector;
  codeSummarizer: CodeSummarizer;
  staticAnalyzer: StaticAnalyzer;
  cryptoDetector: CryptoDetector;
  riskScorer: RiskScorer;
  sessionReporter: SessionReporter;
  explainEngine: ExplainEngine;
  deobfuscator: Deobfuscator;
  requestChainCorrelator: RequestChainCorrelator;
  reverseReportBuilder: ReverseReportBuilder;
  rebuildBundleExporter: RebuildBundleExporter;
  rebuildRunner: RebuildRunner;
  envAccessLogger: EnvAccessLogger;
  fixtureExtractor: FixtureExtractor;
  divergenceComparator: DivergenceComparator;
  patchAdvisor: PatchAdvisor;
  patchPlanManager: PatchPlanManager;
  patchApplier: PatchApplier;
  patchLoopRunner: PatchLoopRunner;
  acceptanceRecorder: AcceptanceRecorder;
  fixtureStabilizer: FixtureStabilizer;
  patchWorkflowRunner: PatchWorkflowRunner;
  patchReportBuilder: PatchReportBuilder;
  rebuildWorkflowRunner: RebuildWorkflowRunner;
  rebuildReportBuilder: RebuildReportBuilder;
  hookManager: HookManager;
  networkCollector: NetworkCollector;
  requestInitiatorTracker: RequestInitiatorTracker;
  xhrWatchpointManager: XhrWatchpointManager;
  evidenceStore: EvidenceStore;
  reverseWorkflowRunner: ReverseWorkflowRunner;
  analyzeTargetRunner: AnalyzeTargetRunner;
}
